### ISSUE TITLE
test_fuzzer.py error

### ISSUE THREAD

**Issue by ronakdborad** [shellphish/fuzzer#11]
Hi,

While testing the fuzzer with the given test script, it is stopping with below error.

ERROR   | 2017-02-03 16:35:01,011 | fuzzer.fuzzer | AFL Error: Pipe at the beginning of core_pattern
Traceback (most recent call last):
  File "test_fuzzer.py", line 124, in <module>
    run_all()
  File "test_fuzzer.py", line 121, in run_all
    all_functions[f]()
  File "test_fuzzer.py", line 76, in test_fuzzer_spawn
    f = fuzzer.Fuzzer(binary, "work")
  File "/home/rborad/driller/local/lib/python2.7/site-packages/fuzzer/fuzzer.py", line 46, in __init__
    Fuzzer._perform_env_checks()
  File "/home/rborad/driller/local/lib/python2.7/site-packages/fuzzer/fuzzer.py", line 496, in _perform_env_checks
    raise InstallError("execute 'echo core | sudo tee /proc/sys/kernel/core_pattern'")
fuzzer.fuzzer.InstallError: execute 'echo core | sudo tee /proc/sys/kernel/core_pattern'

Can anyone help to resolve it.

Thanks

**Comment by zardus** [comment]
It literally says how to resolve it right in the exception :-)

**Comment by ronakdborad** [comment]
Thanks.
