### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Sn0keR4xor** [shellphish/fuzzer#20]
Hello... I'm Having a little bug, after installation I tried to run a single test app, steps to repeoduce:

```
#include <stdio.h>

int main(int argc, char **argv){
	printf("My name is: %s\n",argv[1]);
}
```
Complation
`gcc test.c `

` shellphuzz -i -c 4 ~/Desktop/a.out `

output:
```
[*] Creating fuzzer...
Traceback (most recent call last):
  File "/home/user/anaconda2/bin/shellphuzz", line 63, in <module>
    create_dictionary=not args.no_dictionary, stuck_callback=stuck_callback
  File "/home/user/anaconda2/lib/python2.7/site-packages/fuzzer/fuzzer.py", line 155, in __init__
    p = angr.Project(binary_path)
  File "/home/user/anaconda2/lib/python2.7/site-packages/angr/project.py", line 146, in __init__
    raise Exception("Not a valid binary file: %s" % repr(thing))
Exception: Not a valid binary file: '-i'
Exception AttributeError: "'Fuzzer' object has no attribute '_timer'" in <bound method Fuzzer.__del__ of <fuzzer.fuzzer.Fuzzer object at 0x7f51100fc050>> ignored

```

**Comment by salls** [comment]
It looks like your installation of https://github.com/shellphish/fuzzer is out of date

**Comment by Sn0keR4xor** [comment]
Ooh, maybe... I'm installing now with `/usr/bin/pip` instead of anaconda wrapper!!1 Hope it works...

**Comment by Sn0keR4xor** [comment]
HI, I'm using the script mode, and are working good!
