### ISSUE TITLE
What causes this error?

### ISSUE THREAD

**Issue by winmin** [shellphish/fuzzer#29]
root@a57c22203b68:/ctf/work# shellphuzz /ctf/work/fm
WARNING | 2018-08-08 16:19:59,460 | claripy | Claripy is setting the recursion limit to 15000. If Python segfaults, I am sorry.
[*] Creating fuzzer...
Traceback (most recent call last):
  File "/usr/local/bin/shellphuzz", line 69, in <module>
    create_dictionary=not args.no_dictionary, stuck_callback=stuck_callback, time_limit=args.timeout
  File "/usr/local/lib/python2.7/dist-packages/fuzzer/fuzzer.py", line 162, in __init__
    self.os = p.loader.main_object.os
AttributeError: 'Loader' object has no attribute 'main_object'

**Comment by rhelmot** [comment]
Your version of angr looks extremely old, more than a year out-of-date by
the looks of things. How did you install it?

**Comment by WinMin** [comment]
ok...i use the docker...so...angr  version too old.
