### ISSUE TITLE
unable to fuzz bsdtar on docker

### ISSUE THREAD

**Issue by genewitch** [shellphish/fuzzer#38]
(angr) angr@ee8fe98b1fc4:$ shellphuzz -i -c 27 -d 13 libarchive/bsdtar
[\*] Drilling...
[\*] Creating fuzzer...
Traceback (most recent call last):  
  File "/home/angr/.virtualenvs/angr/bin/shellphuzz", line 7, in \<module\>
    exec(compile(f.read(), \_\_file_\_, 'exec'))
  File "/home/angr/angr-dev/fuzzer/shellphuzz", line 87, in \<module\>
    memory=args.memory, seeds=seeds, timeout=args.run_timeout, protocol_fuzz=args.opc_afl,
AttributeError: 'Namespace' object has no attribute 'opc_afl'
(angr) angr@ee8fe98b1fc4:~$

All set up with `docker run -it shellphish/mechaphish`; `git clone https://github.com/libarchive/libarchive`; compiling libarchive[1], then running the above command.

[1] `cd libarchive/build && ./autogen.sh && cd .. && ./configure && make -j40`

**Comment by genewitch** [comment]
is it an easy fix like run the extremely_easy_setup.sh script in angr-dev? that's what i am doing right now

**Comment by rhelmot** [comment]
you want `./git_all.sh pull` first. you gotta actually update all the repositories.

**Comment by genewitch** [comment]
Double requirement given: shellphish-qemu==0.9.8 from file:///home/angr/angr-dev/wheels/shellphish_qemu-0.9.8-py2.py3-none-manylinux1_x86_64.whl (already in shellphish-qemu==0.9.10 from file:///home/angr/angr-dev/wheels/shellphish_qemu-0.9.10-py2.py3-none-manylinux1_x86_64.whl, name='shellphish-qemu')

after `./git-all.sh pull`; that error came from the "extremely-simple-setup.sh" script. shellphuzz does start now, and there's a lot of scrolling dark blue "error" lines, but i'll tackle that later. 

The ./git-all.sh command also asked me to set a commit message for "/home/angr/angr-dev/wheels/.git/MERGE_MSG" Merge branch 'master' of https://github.com/angr/wheels - i'm no git expert but i've never had to enter my email and whatnot to update/get a repo before.

I'm only using the docker because i couldn't get pip to install driller due to dpkt-fix (among other things). if there's some way i can help in my aforementioned fuzzy-brained capacity i'd be happy to.

**Comment by rhelmot** [comment]
the wheels repo is our poor-man's pypi instance for wheels for which we don't control the distribution or can't go on real pypi bc they're too big. We don't actually use it ever as a real version control repository, we just force-push to it whenever we want to update it because it's full of zillion-megabyte binary files. You want `git reset --hard origin/master`. Then, you want `pip install ./shellphish_qemu-0.9.10-py2.py3-none-manylinux1_x86_64.whl`, to install the binary version of shellphish-qemu in the wheels so you don't have to suffer through building it yourself.
