### ISSUE TITLE
ImportError when trying to fuzz

### ISSUE THREAD

**Issue by Elothis** [shellphish/fuzzer#39]
Hey,

I have successfully installed everything in a virtual environment and am now trying to fuzz a simple c-program with the following command:
`shellphuzz -i -c 1 -d 1 /home/user/local_fuzzing/target/target_binary`

When running this, i get the following error outputs:
`WARNING | 2019-01-04 12:54:46,354 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
Traceback (most recent call last):
  File "/home/user/local_fuzzing/shellphish-afl/venv/bin/shellphuzz", line 10, in <module>
    import driller
ImportError: No module named driller
`

Can anyone help me out with this? Is the angr error causing the ImportError and thats the reason for the crash? Or is just a warning I could ignore and the ImportError itself is the source of the crash? How do I fix it?

Thanks!

Addition:
For installation, I simply created a new virtual environment, activated into it and then ran the 2 commands like specified in the ReadMe here:
`pip install git+https://github.com/shellphish/shellphish-afl`
`pip install git+https://github.com/shellphish/fuzzer`

**Comment by rhelmot** [comment]
The error indicates you need the driller module installed, i.e.
shellphish/driller.

**Comment by Elothis** [comment]
Hi,
thanks for your response. Doing a `pip install git+https://github.com/shellphish/driller` actually solved that ImportError, but now I just get the next one:
`Traceback (most recent call last):
  File "/home/user/local_fuzzing/shellphish-afl/venv/bin/shellphuzz", line 10, in <module>
    import driller
  File "/home/user/local_fuzzing/shellphish-afl/venv/local/lib/python2.7/site-packages/driller/__init__.py", line 1, in <module>
    from .driller_main import *
  File "/home/user/local_fuzzing/shellphish-afl/venv/local/lib/python2.7/site-packages/driller/driller_main.py", line 11, in <module>
    import tracer
ImportError: No module named tracer
`

There does not seem to be anything like shellphish/tracer, does it? What is missing now?
Is there no complete installation guideline on how to setup driller? I simply want to use driller to fuzz and followed the instructions in the ReadMe here (which did not even tell me to do the install /shellphish/driller part you just told me).
So, what do I have to install exactly to make the `shellphuzz -i -c 1 -d 1 /home/user/local_fuzzing/target/target_binary` command work? Up to this point I did the following 3:
`pip install git+https://github.com/shellphish/shellphish-afl`
`pip install git+https://github.com/shellphish/fuzzer`
`pip install git+https://github.com/shellphish/driller`
All inside my virtual environment. Anything else I need to fix the ImportError named above or anything that would pop up after fixing this one as well?

Thank you very much :)

**Comment by zardus** [comment]
For your own sanity, I strongly advise using the shellphish/mechaphish
docker image instead of setting driller up yourself.
